---
- name: playbook for copy files and folder
  hosts: all
  become: true
  tasks:
    - name: copy file 
      copy:
        src: /home/ansadmin/amar
        dest: /etc/ansible/amar
        mode: '0777'
        owner: ansadmin
        directory_mode: '0755'
