---
- name: playbook for install httpd
  hosts: all
  become: true
  tasks: 
     - name: install httpd
       yum:
          name: httpd
          state: present
       when: ansible_os_family == "RedHat"

     - name: httpd start
       service:
          name: httpd
          state: started
       when: ansible_os_family == "RedHat"
