---
- name: playbook for create user with vars
  hosts: all
  become: true
  vars:
    - user: sunil
  tasks:
    - name: crate user {{sunil}}
      user:
        name: "{{user}}"
        state: present
