---
- name: this playbook will create user name
  hosts: all
  become: true
  tasks: 
    - name: create user name shiv
      user: name=shiv state=present    #first method 

    - name: create user name avanish             # second method
      user: 
         name: avanish
         uid: 111
         shell: /bin/bash                  # create user with home directory
         comment: "test user"
         groups: root,ansadmin
         append: yes

           # we can use chatgpt to get yamal script
