---
- name: playbook for remove file or directory
  hosts: all
  become: true
  tasks:
    - name: remove directory
      file:
        path: /etc/ansible/test_dir/firt_file
        state: absent
        mode: '0777'
        owner: ansadmin
        group: ansadmin
