---
- name: playbook for install tomcat
  hosts: all
  become: true
  tasks:
    - name: install java first 
      yum:
        name: java
        state: present
    - name: download tomcat
      get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.tar.gz
        dest: /opt/
    - name: extract package
      unarchive:
        src: "/opt/apache-tomcat-9.0.90.tar.gz"
        dest: "/opt"
        remote_src: yes
        mode: '777'
    - name: giveing permission to .sh file
      file:
        path: /opt/apache-tomcat-9.0.90/bin/startup.sh
        mode: "777"
    - name: run the shell script
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.90/bin
