---
- name: playbook for call to variable from list
  hosts: all
  become: true
  vars_files:
  - user_list.yml
  tasks:
    - name: create user's from list
      user:
       name: "{{user2}}"
       state: present
